ofile=open("fasta.txt","w")
list_seq = [(TCAGAACTGGGTACCGGGGGCTACGGTTATCTTCGCCTTAAGTAATCGTGGAGCGCAGAG
GTGCACTGTACGTTATGGCAATAGTGTTAATTCCGTGAGAAGATGACTTAGCCCGGTCGG
ATGTAGAGTGTCCCGAAAACGGCAAATGCGCCATTGGCTGGGCTGTGTTCGGGAAATTGG
CGGGCCGCTTTGATATCCCCCTGACGCAGAGCAGACACTCATAGGCGTAACATACGGCGA
CCAACGACGGCAGAAGTCGCGCCGATCCCGGGTTCGGCACCCCCAAAGCCAGAAAGGTAC
TGAAGGTCATCGGCCTGGCGCAGGCATTGTAACCATTTGGCTAGCGCACATATTCTTCAT
GAAGTACGCGCATACCCTTGGAAAGGCCTAGCCACGGGTCGCCTGATAGGTTCACCCCTT
ACGAACCTTGCGAACTATAACGTAAAGCAGTACAACTCTAACGTACAGTGCTGCGTGCGA
ATGTACCTGTTACAACCTAAGCAGCGCTGGCCCTACTCGACTCGTCAAACACCAACTCAT
AAAGTACCTTACGCGCGTTCCCACTCGCACATCCGGATTGCGGGGAACCTTGATGAGTGT
ACTCAACTGGTAGAAAACAGTAGTCCCGCTTCAATGACTTTGACGACGTCAACCCGCCAC
CTACTCAGATAGAGGGCTGACCATCTTAAAGGCAGGAGAGCGTGTCATCCTTTTACTCTA
AGTAGGTTGATCAGACGTGTTTCTGCGAGTCGCTAAGGGAGAGATAGAATGCACCGTAGG
TACAAAATCGCCCCTGCGTCGATTCAAACGTCCTCGACTCGTTACAGCTCTGCTCTCATG
TCCCTATGGCACCACTGTGCAAACCAAACAAGGTGGATTTCCGGGGAGTTCCTCCCATTT
GGGGCGTCACCATT),"""GATCAGAAGTGGCTTCATCGGTACACGTCTCAACCTAGTCGAGTAACACAGATGGTATTG
AAGCACAACGTAACTGTGAGGCAAAGATATATCAACGATGATCGCTCAGCGGGATGCTCC
ACCCTGTGAAGGACACATTCTTCGAATGCGGAACGCCTGCCCTGGGGGCCCGCGCAGAAC
TGTACCCTGGGCGACAAGCCCTCGGCGGTCGGCCAGAAGCGTCGAATTAAACTGTGGCAC
TGGAAACCTCTAGTTAATAGTATGCGCAAGCAAACTAGTAGGTAAGTAACCAAAGTATAG
ACGCCAAAGCACTTTATAGTTTTGACGTTCTTCCAGTCTTTTAATTACGGACCCGACACA
AATTATTGGAAGTACGCATCGTCGAAGCCGTGGTGAGCGTACTCATCTCCCCTGACCTTA
TTGGTTGCCCAGCCGAAGGATGAGCGAGCATAGAGCAAAGACCGGTCGCAGGATCTCGCA
GTCGTACATATAGGCACCGTTTCTACGATTTCGTGTGCCCTGTGGGTTAACTTTAACGTA
TGGCGGTGCCTACAAACTAAGTGTCAAGTGTATATCTCCTCGGAGTGCATAAATTTTACT
CGCTATGAAAATAGGCCGTCCAGACTAACCCCATGATTGCCGGCCCCCAGGTAGTGTCAT
AAGGGTCCTCGTTCAGATCCTGGATAATGAGCCAAGCTTGACACTGTGCCTAAAGATCGA
GTGGTTTAGGGGTATGCTGCTATGGCGTCGATATTCAGTGACAAGGCCAACGCCTTTCGG
AACTTTATAGCGCCTTATATACACGTCCGTGAGCGGGAGGGCCTAGCGTGAAACTTTTGA
GAAAGGGTCTAAT """]
list_name = ['>Rosalind_6686','>Rosalind_8823' ]
for i in range(len(list_seq)):
		ofile.write(">" + list_name[i] + "\n" +list_seq[i] + "\n")
ofile.close()
f=open("fasta.txt","r")
line = f.readlines()
print(line)
'''k=''.join(str(x) for x in line)
#print(k)
e=k.count('G')
print(e)'''
'''def percent_gc(st):
	t=st.count('G')
	e=st.count('C')
	z=t+e/len(st)*100
	print(z)
for i in range(len(lines)):
		if i%2!=0:
			#percent_gc(lines[i])
			print(lines[i])'''
